import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "./components/server/Header";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { lightTheme, darkTheme } from "./theme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import getTheme from "./serverFunctions/themeFunctions/getTheme";

const poppins = Poppins({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Todo App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const theme = await getTheme();
    // console.log(theme);
    return (
        <html lang="en">
            <AppRouterCacheProvider options={{ key: "css" }}>
                <ThemeProvider theme={theme == "dark" ? darkTheme : lightTheme}>
                    <CssBaseline />
                    <body className={poppins.className}>
                        <Header />
                        {children}
                    </body>
                </ThemeProvider>
            </AppRouterCacheProvider>
        </html>
    );
}
